#define API_URL @"http://www.naturaldateandtime.com"
//#define API_URL @"http://127.0.0.1:8080/"
#define APPLICATION_NAME @"Natural Date and Time"
#define EMAIL_ADDRESS @"naturaldatetime@idarko.com"
#define WEBSITE_URL @"http://www.naturaldateandtime.com"
#define TWITTER_URL @"http://www.twitter.com/naturaldatetime"
#define CLIENT @"iphone"
#define VERSION @"1.0"
#define VERSION_URLFORMATTED @"1_0"
#define API_SECURITY_TOKEN_SALT @"Of4jbqxqxL91YzD"
